M48
; DRILL file {KiCad 7.0.1-0} date 2023 April 22, Saturday 10:08:43
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-22T10:08:43-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X2.8484Y-5.0394
T2
X2.7898Y-4.1132
X2.7898Y-4.8632
T3
X1.9685Y-3.1496
X1.9685Y-5.3543
X3.8583Y-3.1496
X3.8583Y-5.3543
T0
M30
