---
title: "Harware List"
author: 
  - "Federico Dallo"
  - "Naichen Zhao"
date: "2022-09-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# List of modules

## Box 1: Data Communication 

The data communication box will receive data (UART) from `Box 2: Data Collection` and will be powered (9V - 5V) with the `Box 3: Power Supply`.

The PCB have to be design to act both as `receiver` and `transceiver` and capable to plug-in commercial components:

- Raspberry Pi Zero ([3B+](https://www.raspberrypi.com/products/raspberry-pi-3-model-b-plus/), [Zero](https://www.raspberrypi.com/products/raspberry-pi-zero-2-w/)) 
- Arduino [Nano BLE](https://store-usa.arduino.cc/products/arduino-nano-33-ble?selectedStore=us)
- [ESP32-S3-MINI-1](https://www.adafruit.com/product/5477)
   - [documentation](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html)
- [Feather Huzzah ESP8266](https://www.adafruit.com/product/2821)

Additional modules that should be integrated in the PCB:

- [LoRa 868MHz](https://www.adafruit.com/product/3072)
  - [alternative](https://www.digikey.com/en/products/detail/seeed-technology-co.,-ltd/109990166/7033232?utm_adgroup=RF%20Transceiver%20Modules&utm_source=google&utm_medium=cpc&utm_campaign=Shopping_Product_RF%2FIF%20and%20RFID_NEW&utm_term=&utm_content=RF%20Transceiver%20Modules&gclid=CjwKCAjwpqCZBhAbEiwAa7pXeRL7nhQhQ7vTGvsG-45Smy6gd5Uc4cDUkz6kC4OnWObWKTFqP0Ql0xoCmRAQAvD_BwE)
- Temperature/Humidity/Pressure [BME280](https://www.adafruit.com/product/2652)
- [RTC](https://www.adafruit.com/product/3013)

The connectors that should be on the board:

- Power (USB-C) *Note: the connection should be protected inside the box, with a kind of internal "winding" of the wire to prevent detachment from the board
- [SMA (example)](https://www.adafruit.com/product/1865) 
- [3-pins power connector](https://www.amazon.com/CNLINKO-Industrial-Connector-Receptacles-Waterproof/dp/B06XFM835T/ref=asc_df_B06XFM835T/?tag=hyprod-20&linkCode=df0&hvadid=309764501757&hvpos=&hvnetw=g&hvrand=15304547746607914750&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9032083&hvtargid=pla-572365072529&psc=1)
- [4-pins data communication connector](https://www.amazon.com/CNLINKO-Industrial-Connector-Receptacles-Waterproof/dp/B06XFMQHWM/ref=sr_1_3?crid=33AKG98EDODT9&keywords=CNLINKO+4+Pin+Power+Industrial+Circular+Connector&qid=1664912760&qu=eyJxc2MiOiIyLjEzIiwicXNhIjoiMS41NCIsInFzcCI6IjEuMzcifQ%3D%3D&s=electronics&sprefix=cnlinko+4+pin+power+industrial+circular+connector%2Celectronics%2C183&sr=1-3)

Notes:

- 868 MHz antenna
  - (Taoglass)[https://www.taoglas.com/product/barracuda-omb-868-05f21-868mhz-omni-directional-outdoor-antenna/]




