M48
; DRILL file {KiCad (6.0.10-0)} date Wednesday, January 18, 2023 at 05:39:10 pm
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-18T17:39:10-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.7898Y-4.1132
X2.7898Y-4.8632
T2
X1.9685Y-3.1496
X1.9685Y-5.3543
X3.8583Y-3.1496
X3.8583Y-5.3543
T0
M30
